# Generated by Django 3.1.9 on 2021-07-16 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('departure', models.DateTimeField(default=datetime.datetime(2021, 7, 16, 13, 27, 44, 738647))),
                ('duration', models.DurationField(help_text='Duration for flight in hh:mm:ss format')),
                ('status', models.CharField(choices=[('m', 'Maintenance'), ('d', 'Delay'), ('a', 'Available'), ('f', 'Full'), ('c', 'Cancel')], default='a', help_text='Flight Availability', max_length=1)),
            ],
        ),
    ]
