# Generated by Django 3.1.9 on 2021-07-16 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 13, 27, 57, 129219)),
        ),
    ]
